# Continuous Integration (CI) pipeline that orchestrates the training, evaluation, and registration of the diabetes_regression model.

resources:
  containers:
  - container: mlops
    endpoint: 'acrconnection'
    image: 'automl/mlops/python:latest'

    # image: mcr.microsoft.com/mlops/python:latest
pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - .pipelines/
    - Automated_ML/
    - Automated_ML/02_AutoML_Training_Pipeline/02_AutoML_Training_Pipeline.ipynb
 
variables:
#- template: diabetes_regression-variables-template.yml
- group: devopsforai-aml-vg

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Model_CI'
  displayName: 'Model CI'
  jobs:
  - job: "Model_CI_Pipeline"
    displayName: "Model CI Pipeline"
    container: mlops
    timeoutInMinutes: 0
    variables:
      PASSWORD: $(Build.ArtifactStagingDirectory/drop)
      #PASSWORD: $[dependencies.secret_getter.outputs['getpassword.PASSWORD'] ]
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: $(azureSubscription)
        KeyVaultName: $(KeyVaultName)
        SecretsFilter: '*'
        RunAsPreJob: false

    #- template: code-quality-template.yml
    - task: AzureCLI@1
      inputs:
        azureSubscription: $(azureSubscription)
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: |
          set -e # fail on error
          # Invoke the Python building and publishing a training pipeline
          export connectionString=$(connectionString)
          export subscription_id=$(subscription_id)
          jupyter nbconvert --to script $(pwd)/Automated_ML/02_AutoML_Training_Pipeline/02_AutoML_Training_Pipeline.ipynb
          python $(pwd)/Automated_ML/02_AutoML_Training_Pipeline/02_AutoML_Training_Pipeline.py
      displayName: 'Publish Azure Machine Learning Pipeline'

