# Continuous Integration (CI) pipeline that orchestrates the training, evaluation, and registration of the diabetes_regression model.
parameters:
- name: projectname
  displayName: Project Name
  type: string
  default: Many-Models
  values:
  - Single-Project
  - Forecast
  - FB-Prophet
  - Many-Models
- name: myStringName
  type: string
  default: a string value  

resources:
  containers:
  - container: mlops
    endpoint: 'azurecrconnection'
    image: 'automl/mlops/python:latest'
pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - .pipelines/
    - test2.py
    - test3.py
 
variables:
#- template: diabetes_regression-variables-template.yml
- group: devopsforai-aml-vg

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Model_CI'
  displayName: 'Model CI'
  jobs:
  - job: "Model_CI_Pipeline"
    displayName: "Model CI Pipeline"
    container: mlops
    timeoutInMinutes: 0
    variables:
      PASSWORD: $(Build.ArtifactStagingDirectory/drop)
      #PASSWORD: $[dependencies.secret_getter.outputs['getpassword.PASSWORD'] ]
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: '$(AMLCONNECTION)'
        KeyVaultName: $(A_KV_NAME)
        SecretsFilter: '*'
        RunAsPreJob: false

    #- template: code-quality-template.yml
    - task: AzureCLI@1
      inputs:
        azureSubscription: $(AMLCONNECTION)
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: |
          set -e # fail on error
          echo 'this is the parameter selected: ' ${{parameters.projectname}}
          echo 'did my value for the string come through' ${{parameters.myStringName}}
          # Invoke the Python building and publishing a training pipeline
          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          python -m test2
          python -m test3
      displayName: 'Publish Azure Machine Learning Pipeline'
