name: training_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.7.*
  - pip
  - jupyter

  - pip:
      # Base AzureML SDK
      - azureml-sdk==1.34
      - azureml-train-automl==1.34
      - azureml-contrib-automl-pipeline-steps==1.34
